CXX = g++
CXXFLAGS = -Wall -Wextra -g -std=c++17
LDFLAGS = 
TESTS_EXECUTABLE = tests
BIN_SEARCH_BTREE_EXP_EXECUTABLE = experiments_bin_search_btree
GET_EXP_EXECUTABLE = experiments_get
PUT_EXP_EXECUTABLE = experiments_put
SCAN_EXP_EXECUTABLE = experiments_scan

BUILD_DIR = build
SRC_DIR = src
TEST_DIR = test_files
EXPERIMENTS_DIR = experiments_files
TEST_DB = testdb
INCLUDE_DIR = include

LIB_SOURCES = $(wildcard $(SRC_DIR)/*.cpp)

TEST_MAIN = $(TEST_DIR)/mrkdb_tests.cpp

EXPERIMENT_SEARCH = $(EXPERIMENTS_DIR)/experiment_bin_search_btree.cpp
EXPERIMENT_PUT = $(EXPERIMENTS_DIR)/experiment_put.cpp
EXPERIMENT_GET = $(EXPERIMENTS_DIR)/experiment_get.cpp
EXPERIMENT_SCAN = $(EXPERIMENTS_DIR)/experiment_scan.cpp

LIB_OBJECTS = $(patsubst $(SRC_DIR)/%.cpp, $(BUILD_DIR)/%.o, $(LIB_SOURCES))

TEST_OBJECT = $(BUILD_DIR)/mrkdb_tests.o
EXPERIMENT_OBJECT = $(BUILD_DIR)/experiments.o
EXPERIMENT_SEARCH_OBJECT = $(BUILD_DIR)/experiment_bin_search_btree.o
EXPERIMENT_PUT_OBJECT = $(BUILD_DIR)/experiment_put.o
EXPERIMENT_GET_OBJECT = $(BUILD_DIR)/experiment_get.o
EXPERIMENT_SCAN_OBJECT = $(BUILD_DIR)/experiment_scan.o

TEST_OBJECTS = $(LIB_OBJECTS) $(TEST_OBJECT)

EXPERIMENT_OBJECTS = $(LIB_OBJECTS) $(EXPERIMENT_OBJECT)
EXPERIMENT_SEARCH_OBJECTS = $(LIB_OBJECTS) $(EXPERIMENT_SEARCH_OBJECT)
EXPERIMENT_PUT_OBJECTS = $(LIB_OBJECTS) $(EXPERIMENT_PUT_OBJECT)
EXPERIMENT_GET_OBJECTS = $(LIB_OBJECTS) $(EXPERIMENT_GET_OBJECT)
EXPERIMENT_SCAN_OBJECTS = $(LIB_OBJECTS) $(EXPERIMENT_SCAN_OBJECT)

OBJECTS = $(LIB_OBJECTS) $(TEST_OBJECT) $(EXPERIMENT_OBJECT) $(EXPERIMENT_SEARCH_OBJECTS) $(EXPERIMENT_PUT_OBJECTS) $(EXPERIMENT_GET_OBJECTS) $(EXPERIMENT_SCAN_OBJECTS)

all: $(BUILD_DIR) $(TESTS_EXECUTABLE) $(EXPERIMENTS_EXECUTABLE) $(BIN_SEARCH_BTREE_EXP_EXECUTABLE) $(GET_EXP_EXECUTABLE) $(PUT_EXP_EXECUTABLE) $(SCAN_EXP_EXECUTABLE)

$(BUILD_DIR):
	mkdir -p $@

$(TESTS_EXECUTABLE): $(TEST_OBJECTS)
	$(CXX) $(TEST_OBJECTS) -o $@ $(LDFLAGS)

$(EXPERIMENTS_EXECUTABLE): $(EXPERIMENT_OBJECTS)
	$(CXX) $(EXPERIMENT_OBJECTS) -o $@ $(LDFLAGS)

$(BIN_SEARCH_BTREE_EXP_EXECUTABLE): $(EXPERIMENT_SEARCH_OBJECTS)
	$(CXX) $(EXPERIMENT_SEARCH_OBJECTS) -o $@ $(LDFLAGS)

$(GET_EXP_EXECUTABLE): $(EXPERIMENT_GET_OBJECTS)
	$(CXX) $(EXPERIMENT_GET_OBJECTS) -o $@ $(LDFLAGS)

$(PUT_EXP_EXECUTABLE): $(EXPERIMENT_PUT_OBJECTS)
	$(CXX) $(EXPERIMENT_PUT_OBJECTS) -o $@ $(LDFLAGS)

$(SCAN_EXP_EXECUTABLE): $(EXPERIMENT_SCAN_OBJECTS)
	$(CXX) $(EXPERIMENT_SCAN_OBJECTS) -o $@ $(LDFLAGS)
	
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) -I$(INCLUDE_DIR) -c $< -o $@

$(BUILD_DIR)/mrkdb_tests.o: $(TEST_DIR)/mrkdb_tests.cpp
	$(CXX) $(CXXFLAGS) -I$(INCLUDE_DIR) -c $< -o $@

$(BUILD_DIR)/experiments.o: $(EXPERIMENTS_DIR)/experiments.cpp
	$(CXX) $(CXXFLAGS) -I$(INCLUDE_DIR) -c $< -o $@

$(BUILD_DIR)/experiment_bin_search_btree.o: $(EXPERIMENTS_DIR)/experiment_bin_search_btree.cpp
	$(CXX) $(CXXFLAGS) -I$(INCLUDE_DIR) -c $< -o $@

$(BUILD_DIR)/experiment_get.o: $(EXPERIMENTS_DIR)/experiment_get.cpp
	$(CXX) $(CXXFLAGS) -I$(INCLUDE_DIR) -c $< -o $@

$(BUILD_DIR)/experiment_put.o: $(EXPERIMENTS_DIR)/experiment_put.cpp
	$(CXX) $(CXXFLAGS) -I$(INCLUDE_DIR) -c $< -o $@

$(BUILD_DIR)/experiment_scan.o: $(EXPERIMENTS_DIR)/experiment_scan.cpp
	$(CXX) $(CXXFLAGS) -I$(INCLUDE_DIR) -c $< -o $@

.PHONY: all clean

clean:
	rm -rf $(BUILD_DIR) $(EXECUTABLE) $(TEST_DB) tests experiments experiments_bin_search_btree experiments_get experiments_put experiments_scan exp_scan exp_db_bin exp_db_btree exp_put exp_get